path.data: $[[env.SUITES_NAME]]/data
path.logs: $[[env.SUITES_NAME]]/log

api:
  enabled: true
  network:
    binding: $[[env.LR_GATEWAY_API_HOST]]

entry:
  - name: my_es_entry
    enabled: true
    router: my_router
    max_concurrency: 2000
    network:
      binding: $[[env.LR_GATEWAY_HOST]]

flow:
  - name: test
    filter:
      - elasticsearch:
          elasticsearch: source
  - name: sleep
    filter:
      - sleep:
          sleep_in_million_seconds: 2000
      - echo:
          message: 'ok'

router:
  - name: my_router
    default_flow: test
    rules:
      - method:
          - GET
        pattern:
          - /sleep
        flow: sleep

elasticsearch:
  - name: source
    enabled: true
    endpoints:
      - $[[env.ELASTICSEARCH_ENDPOINT]]
  - name: target
    enabled: true
    endpoints:
      - $[[env.ELASTICSEARCH_ENDPOINT]]

pipeline:
  - name: index_diff_service
    auto_start: false
    keep_running: false
    processor:
    - dag:
        mode: wait_all
        parallel:
          - dump_hash: #dump es1's doc
              sort_document_fields: true
              indices: "test-1"
              scroll_time: "10m"
              elasticsearch: "source"
#              query_string: "_id:c8es70pu46lgfdgmja9g-1646117763293610802-2"
#              fields: "doc_hash"
              output_queue: "source_docs"
              batch_size: 1
              slice_size: 1
#              hash_func: "xxhash64"
          - dump_hash: #dump es2's doc
              indices: "test-2"
              scroll_time: "10m"
#              fields: "doc_hash"
#              query_string: "_id:c8es70pu46lgfdgmja9g-1646117763293610802-2"
              batch_size: 1
              slice_size: 1
#              hash_func: "xxhash64"
              elasticsearch: "target"
              output_queue: "target_docs"
        end:
          - index_diff:
              diff_queue: "diff_result"
              buffer_size: 10
              text_report: false #如果要存 es，这个开关关闭，开启 pipeline 的 diff_result_ingest 任务
              source_queue: 'source_docs'
              target_queue: 'target_docs'
  - name: diff_result_ingest
    auto_start: false
    keep_running: false
    processor:
      - json_indexing:
          idle_timeout_in_seconds: 1
          index_name: "diff_result"
          elasticsearch: "source"
          input_queue: "diff_result"
