configs.template:
  - name: "es_gw1"
    path: ./sample-configs/config_template.tpl
    variable:
      name: "es_gw1"
      binding_host: "0.0.0.0:8000"
      tls_on_entry: true
      elasticsearch_endpoint: "http://localhost:9200"
  - name: "es_gw2"
    path: ./sample-configs/config_template.tpl
    variable:
      name: "es_gw2"
      binding_host: "0.0.0.0:8001"
      tls_on_entry: false
      elasticsearch_endpoint: "http://localhost:9201"
