path.data: data
path.logs: log

entry:
  - name: my_es_entry
    enabled: true
    router: my_router
    max_concurrency: 10000
    network:
      binding: 0.0.0.0:8000
#    tls:
#      enabled: true
#      cert_file: /etc/elasticsearch/certs/es7.crt
#      key_file: /etc/elasticsearch/certs/es7-key.pem
#      skip_insecure_verify: false
flow:
  - name: primary-write-flow
    filter:
      - elasticsearch:
          elasticsearch: es-server
          refresh:
            enabled: true
            interval: 10s
  - name: request_logging
    filter:
#      - record:
#          stdout: true
#          filename: requests.txt
      - logging:
          queue_name: request_logging
          max_request_body_size: 102400
          max_response_body_size: 102400
          when: #>1s or none-200 requests will be logged
            or:
              - not:
                  or:
                    - equals:
                        _ctx.request.path: "/favicon.ico"
                    - in:
                        _ctx.response.status: [200,201]
                    - in:
                        _ctx.request.path: ["/sw.js"]
              - range:
                  _ctx.elapsed.gte: 1000
router:
  - name: my_router
    default_flow: primary-write-flow
    tracing_flow: request_logging

elasticsearch:
  - name: es-server #the business server
    enabled: true
    endpoints:
      - http://192.168.3.188:9206
    basic_auth:
      username: admin
      password: admin
    discovery:
      enabled: true
      refresh:
        enabled: true
        interval: 60s
  - name: logging-server #the logging server
    enabled: true
    endpoints:
      - http://192.168.3.188:9206
    basic_auth:
      username: admin
      password: admin
    discovery:
      enabled: false

pipeline:
  - name: indexing_merge
    auto_start: true
    keep_running: true
    processor:
      - indexing_merge:
          input_queue: "request_logging"
          elasticsearch: "logging-server"
          index_name: "gateway_requests"
          output_queue:
            name: "gateway_requests"
            label:
              tag: "request_logging"
          worker_size: 1
          bulk_size_in_mb: 10
  - name: logging_requests
    auto_start: true
    keep_running: true
    processor:
      - bulk_indexing:
          bulk:
            compress: true
            batch_size_in_mb: 10
            batch_size_in_docs: 5000
          consumer:
            fetch_max_messages: 100
          queues:
            type: indexing_merge
          when:
            cluster_available: [ "logging-server" ]
