env:
  LR_GATEWAY_HOST: 127.0.0.1:8001
  LR_GATEWAY_API_HOST: 127.0.0.1:9000
  ELASTICSEARCH_ENDPOINT: http://127.0.0.1:9200
path.data: data
path.logs: log

api:
  enabled: true
  network:
    binding: $[[env.LR_GATEWAY_API_HOST]]

entry:
  - name: my_es_entry
    enabled: true
    router: my_router
    max_concurrency: 10000
    network:
      binding: $[[env.LR_GATEWAY_HOST]]

flow:
  - name: primary-write-flow
    filter:
      - elasticsearch:
          elasticsearch: es-server
          refresh:
            enabled: true
            interval: 10s
  - name: request_logging
    filter:
      - logging:
          queue_name: request_logging
          max_request_body_size: 102400
          max_response_body_size: 102400
          when: #>1s or none-200 requests will be logged
            or:
              - not:
                  or:
                    - equals:
                        _ctx.request.path: "/favicon.ico"
                    - in:
                        _ctx.request.path: ["/sw.js"]
              - range:
                  _ctx.elapsed.gte: 1000
  - name: sleep
    filter:
      - sleep:
          sleep_in_million_seconds: 20000
      - echo:
          message: 'ok'

router:
  - name: my_router
    default_flow: primary-write-flow
    tracing_flow: request_logging
    rules:
      - method:
          - GET
        pattern:
          - /sleep
        flow: sleep

elasticsearch:
  - name: es-server #the business server
    enabled: true
    endpoints:
      - $[[env.ELASTICSEARCH_ENDPOINT]]
    discovery:
      enabled: true
      refresh:
        enabled: true
        interval: 60s
  - name: logging-server #the logging server
    enabled: true
    endpoints:
      - $[[env.ELASTICSEARCH_ENDPOINT]]
    discovery:
      enabled: false

pipeline:
  - name: indexing_merge
    auto_start: true
    keep_running: true
    processor:
      - indexing_merge:
          input_queue: "request_logging"
          elasticsearch: "logging-server"
          idle_timeout_in_seconds: 1
          index_name: "gateway_requests"
          output_queue:
            name: "gateway_requests"
            label:
              tag: "request_logging"
          worker_size: 1
          bulk_size_in_mb: 10
  - name: logging_requests
    auto_start: true
    keep_running: true
    processor:
      - bulk_indexing:
          bulk:
            compress: true
            batch_size_in_mb: 10
            batch_size_in_docs: 1
          consumer:
            fetch_max_messages: 100
          queues:
            type: indexing_merge
