path.data: data
path.logs: log

entry:
  - name: my_es_entry
    enabled: true
    router: my_router
    max_concurrency: 2000
    network:
      binding: $[[env.LR_GATEWAY_HOST]]

flow:
  - name: test
    filter:
      - elasticsearch:
          elasticsearch: dev
  - name: sleep
    filter:
      - sleep:
          sleep_in_million_seconds: 20000
      - echo:
          message: 'ok'

router:
  - name: my_router
    default_flow: test
    rules:
      - method:
          - GET
        pattern:
          - /sleep
        flow: sleep

elasticsearch:
  - name: dev
    enabled: true
    endpoint: $[[env.LR_ELASTICSEARCH_ENDPOINT]]

pipeline:
  - name: index_backup
    auto_start: true
    keep_running: true
    processor:
      - index_backup:
          elasticsearch: "dev"
          index: "test"
          upload_to_fs_repo: false
          upload_to_s3: true
          upload_interval_in_second: 1
          s3:
            server: my_blob_store
            location: cn-beijing-001
            bucket: $[[env.LR_MINIO_TEST_BUCKET]]

elastic:
  elasticsearch: dev
  enabled: true
  remote_configs: false
  health_check:
    enabled: true
  availability_check:
    enabled: true
  metadata_refresh:
    enabled: true

s3:
  my_blob_store:
    endpoint: $[[env.LR_MINIO_API_HOST]]
    access_key: $[[env.LR_MINIO_API_USERNAME]]
    access_secret: $[[env.LR_MINIO_API_PASSWORD]]
