path.data: data
path.logs: log

entry:
  - name: my_es_entry
    enabled: true
    router: my_router
    max_concurrency: 10000
    network:
      binding: :9243
    tls:
      enabled: true
      cert_file: /elasticsearch.domain.cn.pem
      key_file: /elasticsearch.domain.cn.key
      skip_insecure_verify: false

flow:
  - name: hcy-async-indexing
    filter:
      - http:
          schema: "http"
          hosts:
            - "10.69.91.79:8000"
            - "10.69.91.80:8000"
      - drop:
  - name: bulk_flow
    filter:
      - flow:
          when:
            and:
              - contains:
                  _ctx.request.path: /_bulk
              - prefix:
                  _ctx.request.host: 165ed1e903914b929746c642d92b5a21
          flows:
            - hcy-async-indexing
      - flow:
          flows:
            - default-flow
  - name: default-flow
    filter:
      - http:
          schema: "https" #https or http
          max_idle_conn_duration: "900s"
          hosts:
            - "10.169.172.51:9243"
            - "10.169.172.52:9243"
            - "10.169.172.53:9243"
  - name: request_logging
    filter:
      - logging:
          queue_name: request_logging
          max_request_body_size: 4096
          max_response_body_size: 4096
          when: #>1s or none-200 requests will be logged
            or:
              - not:
                  or:
                    - equals:
                        _ctx.request.path: "/favicon.ico"
                    - in:
                        _ctx.response.status: [200,201]
                    - in:
                        _ctx.request.path: ["/sw.js"]
              - range:
                  _ctx.elapsed.gte: 1000
router:
  - name: my_router
    default_flow: default-flow
    tracing_flow: request_logging
    rules:
      - method:
          - "*"
        pattern:
          - "/_bulk"
          - "/{any_index}/_bulk"
        flow:
          - bulk_flow
          
elasticsearch:
  - name: logging-server
    enabled: true
    endpoints:
      - https://10.169.172.64:9200
    basic_auth:
      username: elastic
      password: password
    discovery:
      enabled: false

pipeline:
  - name: indexing_merge
    auto_start: true
    keep_running: true
    processor:
      - indexing_merge:
          input_queue: "request_logging"
          elasticsearch: "logging-server"
          index_name: "infini_gateway-000001"
          output_queue:
            name: "gateway_requests"
            label:
              tag: "request_logging"
          worker_size: 1
          bulk_size_in_mb: 10
  - name: logging_requests
    auto_start: true
    keep_running: true
    processor:
      - bulk_indexing:
          bulk:
            compress: true
            batch_size_in_mb: 10
            batch_size_in_docs: 5000
          consumer:
            fetch_max_messages: 100
          queues:
            type: indexing_merge
          when:
            cluster_available: [ "logging-server" ]