path.data: data
path.logs: log

elasticsearch:
  - name: dev
    enabled: true
    endpoint: http://localhost:9200

pipeline:
  - name: index_backup
    auto_start: true
    keep_running: true
    processor:
      - index_backup:
          elasticsearch: "dev"
          index: "test"
          upload_to_fs_repo: true
          upload_to_s3: false
          s3:
            server: my_blob_store
            location: cn-beijing-001
            bucket: infini-index-backup
          when:
            cluster_available: [ "dev" ]

elastic:
  elasticsearch: dev
  enabled: true
  remote_configs: false
  health_check:
    enabled: true
  availability_check:
    enabled: true
  metadata_refresh:
    enabled: true

#disk_queue:
#  upload_to_s3: true
#  s3:
#    server: my_blob_store
#    location: cn-beijing-001
#    bucket: infini-store

s3:
  my_blob_store:
    endpoint: "192.168.3.188:9000"
    access_key: "minio"
    access_secret: "miniostorage"
