env:
  LR_GATEWAY_API_HOST: 127.0.0.1:2900
  SRC_ELASTICSEARCH_ENDPOINT: http://127.0.0.1:9200
  DST_ELASTICSEARCH_ENDPOINT: http://127.0.0.1:9200
path.data: data
path.logs: log
progress_bar.enabled: true
configs.auto_reload: true

api:
  enabled: true
  network:
    binding: $[[env.LR_GATEWAY_API_HOST]]

elasticsearch:
  - name: source
    enabled: true
    endpoint: $[[env.SRC_ELASTICSEARCH_ENDPOINT]]
  - name: target
    enabled: true
    endpoint: $[[env.DST_ELASTICSEARCH_ENDPOINT]]


pipeline:
  - name: source_scroll
    auto_start: true
    keep_running: false
    processor:
      - es_scroll:
          slice_size: 1
          batch_size: 5000
          indices: "es_migration-test"
          elasticsearch: source
          output_queue: source_index_dump
          partition_size: 1
          scroll_time: "5m"
          index_rename:
            "*": "es_migration-test-new"
          remove_type: true

  - name: target_indexing
    auto_start: true
    keep_running: true
    processor:
      - bulk_indexing:
          idle_timeout_in_seconds: 1
          elasticsearch: target
          max_worker_size: 10
          detect_active_queue: false
          detect_interval: 100
          bulk:
            compress: true
            batch_size_in_mb: 20
            batch_size_in_docs: 1000
            invalid_queue: bulk_indexing_400
          queues:
            type: scroll_docs
          consumer:
            fetch_max_messages: 1000

disk_queue:
  sync_timeout_in_ms: 10000
  sync_every_records: 10000
