path.data: data
path.logs: log

entry:
  - name: my_es_entry
    enabled: true
    router: my_router
    network:
      binding: 0.0.0.0:8000

flow:
  - name: primary-write-flow
    filter:
      - queue:
          queue_name: "backup"
      - set_response:
          body: '{"success":true}'
          status: 200
          content_type: application/json
      - drop:
  - name: async-write-flow
    filter:
      - elasticsearch:
          elasticsearch: "backup"
router:
  - name: my_router
    default_flow: primary-write-flow

elasticsearch:
  - name: backup
    enabled: true
    endpoints:
      - http://192.168.3.188:9206


pipeline:
  - name: queue_consumer
    auto_start: true
    keep_running: true
    processor:
      - fast_flow_runner:
          input_queue: "backup"
          flow: async-write-flow
