configs.auto_reload: true
path.data: data-async
path.logs: log-async

api:
  enabled: true
  network:
    binding: 0.0.0.0:2901

pipeline:
  - name: metrics_merge
    auto_start: true
    keep_running: true
    processor:
      - indexing_merge:
          input_queue: "metrics"
          elasticsearch: "logging-server"
          index_name: ".infini_metrics"
          output_queue:
            name: "bulk_requests"
            label:
              tag: "metrics"
          worker_size: 1
          bulk_size_in_mb: 10
  - name: request_logging_merge
    auto_start: true
    keep_running: true
    processor:
      - indexing_merge:
          input_queue: "request_logging"
          elasticsearch: "logging-server"
          index_name: ".infini_requests_logging"
          output_queue:
            name: "bulk_requests"
            label:
              tag: "request_logging"
          worker_size: 1
          bulk_size_in_mb: 10
  - name: failure_message_merge
    auto_start: true
    keep_running: true
    processor:
      - indexing_merge:
          input_queue: "bulk_result_messages"
          elasticsearch: "logging-server"
          index_name: ".infini_async_bulk_results"
          output_queue:
            name: "bulk_requests"
            label:
              tag: "bulk_logging"
          worker_size: 1
          bulk_size_in_mb: 10  
  - name: ingest_merged_requests
    auto_start: true
    keep_running: true
    processor:
      - bulk_indexing:
          bulk:
            compress: true
            batch_size_in_mb: 10
            batch_size_in_docs: 5000
          consumer:
            fetch_max_messages: 100
          queues:
            type: indexing_merge
          when:
            cluster_available: [ "logging-server" ]
  - name: bulk_request_ingest
    auto_start: true
    keep_running: true
    retry_delay_in_ms: 1000
    processor:
      - bulk_indexing:
          max_connection_per_node: 1000
          num_of_slices: 10
          max_worker_size: 200
          idle_timeout_in_seconds: 2
          bulk:
            compress: false
            batch_size_in_mb: 40
            batch_size_in_docs: 50000
            dead_letter_queue: "bulk_dead_requests"
            bulk_result_message_queue: "bulk_result_messages"
            max_request_body_size: 10240
            max_response_body_size: 10240
            save_success_results: true
          consumer:
            fetch_max_messages: 1000
          queue_selector:
            labels:
              type: bulk_reshuffle


entry:
  - name: my_es_entry
    enabled: true
    router: my_router
    max_concurrency: 200000
    network:
      binding: 0.0.0.0:8007
    # tls:
    #   enabled: true
    #   cert_file: /data/gateway/cert/elasticsearch.domain.cn.pem
    #   key_file: /data/gateway/cert/elasticsearch.domain.cn.key
    #   skip_insecure_verify: false

flow:
  - name: async_bulk
    filter:
      - bulk_reshuffle:
          when:
            contains:
              _ctx.request.path: /_bulk
          elasticsearch: prod
          level: node
          partition_size: 1
          #shards: [1,3,5,7,9,11,13]
          continue_metadata_missing: true
          fix_null_id: true
      - http:
          schema: "http" #https or http
          hosts:
            #- localhost:9200
            - "uuid.elasticsearch.domain.a:9200"
            # - "uuid.elasticsearch.domain.b:9243"
            # - "uuid.elasticsearch.domain.c:9243"
            # - "uuid.elasticsearch.domain.d:9243"
            # - "uuid.elasticsearch.domain.e:9243"


router:
  - name: my_router
    default_flow: async_bulk

elasticsearch:
  - name: prod
    enabled: true
    endpoints:
     # - http://localhost:9200
      - http://uuid.elasticsearch.domain.a:9200
     # - https://uuid.elasticsearch.domain.b:9243
     # - https://uuid.elasticsearch.domain.c:9243
     # - https://uuid.elasticsearch.domain.d:9243
     # - https://uuid.elasticsearch.domain.e:9243
    discovery:
      enabled: false
    basic_auth:
      username: elastic
      password: password
  - name: logging-server
    enabled: true
    endpoints:
      - http://localhost:9201
    basic_auth:
      username: elastic
      password: password
    discovery:
      enabled: false

elastic:
  enabled: true
  remote_configs: false
  health_check:
    enabled: true
    interval: 30s
  availability_check:
    enabled: true
    interval: 60s
  metadata_refresh:
    enabled: true
    interval: 30s
  cluster_settings_check:
    enabled: false
    interval: 20s

disk_queue:
  prepare_files_to_read: true
  #max_bytes_per_file: 20971520
  compress:
    delete_after_compress: true
    idle_threshold: 20

metrics:
  enabled: true
  queue: metrics
  instance:
    enabled: true
  network:
    enabled: true
    summary: true
