path.data: data
path.logs: log

entry:
  - name: my_es_entry
    enabled: true
    router: my_router
    max_concurrency: 2000
    network:
      binding: 0.0.0.0:8000

flow:
  - name: test
    filter:
      - bulk_reshuffle:
          elasticsearch: prod
          level: node #cluster,node,shard,partition
      - elasticsearch:
          elasticsearch: prod
          refresh:
            enabled: true
            interval: 30s

router:
  - name: my_router
    default_flow: test

elastic:
  enabled: true
  remote_configs: false
  health_check:
    enabled: true
    interval: 30s
  availability_check:
    enabled: true
    interval: 60s
  metadata_refresh:
    enabled: true
    interval: 30s
  cluster_settings_check:
    enabled: false
    interval: 20s

elasticsearch:
  - name: prod
    endpoint: http://localhost:9200
    enabled: true
    discovery:
      enabled: true
      refresh:
        enabled: true
        interval: 30s
pipeline:
  - name: bulk_request_ingest
    auto_start: true
    processor:
      - bulk_indexing:
          bulk_size_in_mb: 10  #in MB
          queues:
            type: bulk_reshuffle
            level: node

#  curl localhost:8000/_bulk -d `{ "index" : { "_index" : "test-bulk", "_id" : "1" } }
#              { "ip":"192.168.0.2" ,"now_with_format":"2023-01-08T14:46:17+0800"}
#            { "index" : { "_index" : "test-bulk", "_id" : "2" } }
#            { "ip":"192.168.0.4" ,"now_with_format":"2023-01-08T14:46:17+0800"}
#            `
#  response: {"took":1675,"errors":false,"items":[{"index":{"_index":"test-bulk","_type":"_doc","_id":"1","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1,"status":201}},{"index":{"_index":"test-bulk","_type":"_doc","_id":"2","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":1,"_primary_term":1,"status":201}}]}