env:
  LR_ELASTICSEARCH_ENDPOINT: http://127.0.0.1:19201
  LR_GATEWAY_HOST: localhost:8000
  LR_GATEWAY_CMD: /Users/kassian/Workspace/infini/src/infini.sh/gateway/bin/gateway
  LR_LOADGEN_CMD: /Users/kassian/Workspace/infini/src/infini.sh/loadgen/bin/loadgen
tests:
  - path: setup/gateway/cases/elasticsearch/elasticsearch-with-cache
  - path: setup/gateway/cases/elasticsearch/elasticsearch-with-cache-plus
  - path: setup/gateway/cases/echo/hello_world
  - path: setup/gateway/cases/echo/echo_with_context
  - path: setup/gateway/cases/echo/dump_context
